### ISSUE TITLE
Weird response from concurrently on exit code 0 

### ISSUE THREAD

**Issue by bjesuiter** [tqwewe/concurrently#3]
I try to repurpose this tool as alternative to the 'concurrently' package on npm. 

This works relatively well right now, but I have a problem: 

When I run the following tasks.toml, concurrently detects the result status of the tasks as non-successful, despite them being 0, and tries to retry them: 

```toml
# This is a demo tasks file intended for development of this concurrently package

# [tasks.endless]
#     command = "while true ; do echo \"Hello from Endless Demo- $(date)\" ; sleep 1 ; done"
#     retries = 3                                                                       # Retry 3 times before exiting
#     delay   = 1000         

# [tasks.tentimes]
#     command = "for i in $(seq 1 10) ; do echo \"Hello from TenTimes Demo - $(date)\" ; sleep 1 ; done"
#     retries = 3                                                                       # Retry 3 times before exiting
#     delay   = 1000                                                                    # Wait 1 second before running

[tasks.demo1]
    command    = "for i in $(seq 1 5) ; do echo \"Hello from Demo 1 - $(date)\" ; sleep 1 ; done; exit 0"
    retries    = 0
    maxRetries = 0                                                                                      # Retry 3 times before exiting
    delay      = 1000                                                                                   # Wait 1 second before running

[tasks.demo2]
    command    = "for i in $(seq 1 5) ; do echo \"Hello from Demo 2 - $(date)\" ; sleep 1 ; done; exit 0"
    retries    = 0
    maxRetries = 0                                                                                      # Retry 3 times before exiting
    delay      = 2000                                                                                   # Wait 2 seconds before running

[tasks.demo3]
    # Run a custom command
    command    = "for i in $(seq 1 5) ; do echo \"Hello from Demo 3 - $(date)\" ; sleep 1 ; done; exit 0"
    retries    = 0
    maxRetries = 0                                                                                      # Retry 3 times before exiting
    delay      = 3000                                                                                   # Wait 3 seconds before running

```

Do you have an idea why this happens or could you maybe even fix it? 
I'm not fluent enough in rust to fix it myself :(
